# - name: Print ansible_os_family
#   ansible.builtin.debug:
#     var: ansible_os_family
#   tags:
#     - always

- set_fact:
    # goos: "{{ 'darwin' if ansible_os_family == 'Darwin' else '' }}"
    goos: "{{ d[ansible_os_family] | default ('unknown-goos') }}"
  vars:
    d: {Darwin: 'darwin', "OtherLinux": "linux"}
  check_mode: no

- set_fact:
    goarch: "{{ d[ansible_architecture] | default ('unknown-goarch') }}"
  vars:
    d: {'arm64': 'arm64', 'x86_64': 'amd64'}
    # goarch: "{{ ansible_architecture if ansible_architecture in ['arm64'] elif ansible_architecture = 'amd64' }}"
    # goarch: "{{ ansible_architecture }}"
  check_mode: no

- name: Install tailscale{,d}
  copy:
    src: tailscale/{{ goos }}-{{ goarch }}/bin/{{ item }}
    dest: /usr/local/sbin
    owner: root
    group: "root"
    mode: 0755
  with_items:
    - tailscale
    - tailscaled

- name: Install tailscale system daemon
  shell: mv /usr/local/sbin/tailscaled /usr/local/sbin/tailscaled-orig && /usr/local/sbin/tailscaled-orig install-system-daemon
  args:
    creates: /Library/LaunchDaemons/com.tailscale.tailscaled.plist
  when: ansible_os_family == 'Darwin'


- name: Check if Tailscale is connected
  command: tailscale status
  changed_when: false
  register: tailscale_status

- name: Tailscale Status
  debug:
    var: tailscale_status
  when: verbose | bool

- name: Get tailscale auth key
  pause:
    prompt: Enter the one-time use tailscale auth key
    echo: no
  register: tailscale_auth_key
  no_log: true
  when: False

- name: Bring Tailscale Up
  become: true
  # The command module cannot use | ; &
  # So we are ok not quoting the variables
  command: /usr/local/bin/tailscale up --authkey={{ tailscale_auth_key.user_input }} {{ tailscale_args | default() }}
  # Since the auth key is included in this task, we do not want to log output
  # no_log: true
  register: tailscale_start
  when: False

  # when: >
  #   and 'hello-ipn-dev' not in tailscale_status.stdout)
  # when: >
  #   force | bool or
  #   (not tailscale_up_skip | bool
  #   and 'hello-ipn-dev' not in tailscale_status.stdout)
  # notify: Confirm Tailscale is Connected
