- name: Convert peer names to host entries
  local_action: "shell echo '{{ wireguard_peer_machine_names | join('\n')}}' | ../bin/names_to_etc_host_entries"
  changed_when: false
  check_mode: no
  register: wg_names_to_etc_host_entries_conversion

- name: set wg_etc_host_entries
  set_fact:
    wg_etc_host_entries: "{{ wg_names_to_etc_host_entries_conversion.stdout_lines }}"
  check_mode: no

- name: add wg hosts to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^\\s*{{ item.split(' ')[0] }}\\s+"
    line: "{{ item }}"
  with_items: "{{ wg_etc_host_entries }}"
  when: (wg_etc_host_entries | length>0)
