- name: get my public IP
  ipify_facts:
  register: ansible_host_public_ip
  connection: local
- set_fact:
     ansible_host_public_ip: "{{ ansible_host_public_ip.ansible_facts.ipify_public_ip }}"
# - debug:
#     var: ansible_host_public_ip
