- name: "Get Facts : Get public IP address"
  ipify_facts:
  register: ansible_host_public_ip
  connection: local

- name: "Get Facts : Set ansible_host_public_ip"
  set_fact:
     ansible_host_public_ip: "{{ ansible_host_public_ip.ansible_facts.ipify_public_ip }}"
