# - name: "Get facts"
#   setup:

# - name: Display all variables/facts known for a host
#   debug:
#     var: hostvars[inventory_hostname]
#   tags: debug_info


- name: Determine if default user has access
  local_action: "command ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ inventory_hostname }} 'echo ok'"
  register: test_user
  ignore_errors: true
  changed_when: false

- name: print test_user
  debug:
    var: test_user

- name: "Get facts"
  setup:
    # gather_subset:
  # At this early stage, we may not have created the real, custom admin account yet,
  # so we may need to specify the remote_user to be root.
  remote_user: "{{ test_user | success | ternary(omit, 'root') }}"

- name: "Get Facts : Get public IP address"
  ipify_facts:
  register: ansible_host_public_ip
  delegate_to: localhost

- name: "Get Facts : Set ansible_host_public_ip"
  set_fact:
     ansible_host_public_ip: "{{ ansible_host_public_ip.ansible_facts.ipify_public_ip }}"
