- name: 'Require mandatory variables'
  assert:
    that:
      - admin_username is defined

- name: Determine if default user has access
  local_action: "command ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ inventory_hostname }} 'echo ok'"
  register: test_user
  ignore_errors: true
  changed_when: false

- name: "Get Facts : Get public IP address"
  ipify_facts:
  register: ansible_host_public_ip
  delegate_to: localhost
  run_once: true

- name: "Get Facts : Set ansible_host_public_ip"
  set_fact:
     ansible_host_public_ip: "{{ ansible_host_public_ip.ansible_facts.ipify_public_ip }}"
