- name: 'setup : Require mandatory variables'
  assert:
    that:
      - admin_username is defined
    fail_msg: "One or more required variables are missing."

- name: Create ssh control directory if it does not exist
  local_action:
    module: file
    path: /root/.ansible/cp
    state: directory
    mode: '0700'
  changed_when: false
  check_mode: no
  tags:
    - always

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: "setup : Set real_ansible_ssh_host"
  set_fact:
     real_ansible_ssh_host: "{{ ansible_ssh_host }}"
  tags:
    - always

# Not certain what's going on, but running this seems to allow subsequent ansible ssh connections to succeed.
# ansible_ssh_host, inventory_hostname, real_ansible_ssh_host
- name: "setup : Connect directly via ssh to enable subsequent ansible ssh connections"
  local_action: "shell ssh -o ControlMaster=auto -o ControlPersist=1800s -o 'User=\"{{ admin_username }}\"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r {{ real_ansible_ssh_host }} '/bin/sh -c '\"'\"'echo ~{{ admin_username }} && sleep 0'\"'\"''"
  changed_when: false
  check_mode: no
  when: not (skip_ssh_setup | default(False))
  tags:
    - always

# ansible_host_public_ip is needed for the firewall and for .google_authenticator
- name: "setup : Get public IP address"
  ipify_facts:
    timeout: 10
  register: ansible_host_public_ip
  delegate_to: localhost
  run_once: true
  changed_when: false
  check_mode: no

- name: "setup : Set ansible_host_public_ip"
  set_fact:
     ansible_host_public_ip: "{{ ansible_host_public_ip.ansible_facts.ipify_public_ip }}"

- name: Collect only facts needed for ansible-role-base
  setup:
    gather_subset:
      - '!all'
      - virtual # used for ansible_os_family
  tags:
    - always

- name: Debug ansible_os_family
  debug:
    var: ansible_os_family
    # verbosity: "1"
  check_mode: no
  tags:
    - always

# - name: Fail
#   fail:
#     msg: Dan fail

- name: "setup : Set wheel_group"
  set_fact:
     wheel_group: "{{ 'wheel' if ansible_os_family == 'Darwin' else 'wheel' }}"
  tags:
    - always

- set_fact:
    # goos: "{{ 'darwin' if ansible_os_family == 'Darwin' else '' }}"
    goos: "{{ d[ansible_os_family] | default ('unknown-goos') }}"
  vars:
    d: {Darwin: 'darwin', "OtherLinux": "linux", "Debian": "linux"}
  check_mode: no
  tags:
    - always

- set_fact:
    goarch: "{{ d[ansible_architecture] | default ('unknown-goarch') }}"
  vars:
    d: {'arm64': 'arm64', 'x86_64': 'amd64'}
    # goarch: "{{ ansible_architecture if ansible_architecture in ['arm64'] elif ansible_architecture = 'amd64' }}"
    # goarch: "{{ ansible_architecture }}"
  check_mode: no
  tags:
    - always

- name: Print ansible_architecture
  ansible.builtin.debug:
    var: ansible_architecture
  tags:
    - always

- name: "setup : apple rosetta"
  set_fact:
     apple_rosetta_cmd: "{{ 'arch -x86_64 ' if ansible_os_family == 'Darwin' and ansible_architecture == 'arm64' else '' }}"
  tags:
    - always

- name: Print apple_rosetta_cmd
  ansible.builtin.debug:
    var: apple_rosetta_cmd
  tags:
    - always

- name: "setup : homebrew prefix"
  set_fact:
     homebrew_prefix: "{{ '/opt/homebrew' if ansible_architecture == 'arm64' else '/usr/local' }}"
  when: ansible_os_family == 'Darwin' and (homebrew_prefix is not defined)
  tags:
    - always

- name: Debug homebrew_prefix
  debug:
    var: homebrew_prefix
    # verbosity: "1"
  check_mode: no
  tags:
    - always

- name: Validate that brew is in the path
  shell: brew --prefix
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ homebrew_prefix }}/sbin:{{ ansible_env.PATH }}"
  when: ansible_os_family == 'Darwin'
  check_mode: no
  changed_when: false
  register: brew_prefix_reg
  tags:
    - always

- name: Debug brew_prefix_reg
  debug:
    var: brew_prefix_reg
    # verbosity: "1"
  check_mode: no
  tags:
    - always

- name: Ensure group "brew" exists
  group:
    name: brew
    state: present
    # gid: "472"
  when: ansible_os_family == 'Darwin'

- name: Set perms for brew directory
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    recurse: yes
    group: brew
    mode: g+w
  when: ansible_os_family == 'Darwin' and (homebrew_prefix != "/usr/local")
  # tags:
  #   - always

- name: Ensure group "brew" exists
  group:
    name: brew
    state: present
    # gid: "472"

- name: Set perms for brew directory
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    recurse: yes
    group: brew
    mode: g+w
