- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add custom user
  user:
    name: "{{ custom_username }}"
    shell: /bin/bash
    groups: wheel
    append: yes

- file:
    path: /home/{{ custom_username }}/.ssh
    state: directory
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: 0755

- name: Install authorized_keys
  copy:
    src: .ssh/authorized_keys
    dest: /home/{{ custom_username }}/.ssh/authorized_keys
    owner: "{{ custom_username }}"
    group: "{{ custom_username }}"
    mode: 0400
- name: Set the immutable bit to prevent changes to ~/.ssh and authorized_keys
  command: chattr +i /home/{{ custom_username }}/.ssh/authorized_keys /home/{{ custom_username }}/.ssh
  changed_when: False
