---
- name: get my public IP
  ipify_facts:
  register: public_ip
  connection: local
- debug:
    var: public_ip
- set_fact:
     public_ip: public_ip.ansible_facts.ipify_public_ip
- debug:
    var: public_ip

# - include: firewall.yml

- include: sshd.yml

- include: postfix.yml

- include: email_routing.yml

- include: package_cleanup.yml

- include: motd.yml

- include: personalize_root.yml

- include: custom_user.yml
