- name: Test user
  local_action: "command ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ inventory_hostname }} 'echo ok'"
  register: test_user
  ignore_errors: true
  changed_when: false

- name: Set remote_user
  remote_user: "{{ test_user | success | ternary(omit, 'root') }}"
  command: echo ok
