- include: 1-postfix.yml

- include: 2-email_routing.yml

- include: 3-package_cleanup.yml

# - include: 3b-do-agent.yml

- include: 4-custom_user.yml

- include: 5-etc_hosts.yml

- include: 6-prometheus_monitoring.yml

- include: 7-digitalocean_monitoring.yml
