- include: 1-postfix.yml
  when: ansible_os_family == 'Debian'

- include: 2-email_routing.yml
  when: ansible_os_family == 'Debian'

- include: 3-package_cleanup.yml
  when: ansible_os_family == 'Debian'

# - include: 3b-do-agent.yml

- include: 4-custom_user.yml
  tags:
    - custom_user

- include: 5-etc_hosts.yml
  when: ansible_os_family == 'Debian'

- include: 6-prometheus_monitoring.yml
  when: ansible_os_family == 'Debian'
  tags:
    - prometheus_monitoring

- include: 7-digitalocean_monitoring.yml
  when: ansible_os_family == 'Debian'

- include: 8-login-tracking.yml
  when: ansible_os_family == 'Debian'
