- name: Keep cloud-init clean
  copy:
    src: etc/cloud/cloud.cfg.d/90_dpkg.cfg
    dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
