- name: Add private IP addresses of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item]["ansible_fqdn"] }}$'
    line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }}"
    state: present
  when: hostvars[item]['ansible_eth1'] is defined
  with_items: "{{ groups.all }}"
