- name: Install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no

- name: "Allow access to node exporter from prometheus server's public ip only and only via eth0"
  ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "{{ utility1_djrtechconsulting_com_public_ip }}"
    direction: in
    interface: eth0

- name: "Allow access to node exporter from prometheus server's vpn ip only and only via vpn"
  ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "10.0.0.1"
    direction: in
    interface: wg0

- name: Create textfile_collector dir
  file:
    path: "/var/lib/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - node_exporter
    - node_exporter/textfile_collector

- name: Update /etc/init.d/prometheus-node-exporter to use textfile_collector
  lineinfile:
    path: /etc/init.d/prometheus-node-exporter
    regexp: 'HELPER_ARGS="--name=$NAME --output=$LOGFILE --pidfile=$PIDFILE --user=$USER"'
    line: 'HELPER_ARGS="--collector.textfile.directory=/var/lib/node_exporter/textfile_collector --name=$NAME --output=$LOGFILE --pidfile=$PIDFILE --user=$USER"'
  notify:
    - Restart prometheus-node-exporter
