# track-login requires the "mail" program which is provided by mailutils
- name: install mailutils
  apt:
    name: mailutils
    state: present
    update_cache: yes
    install_recommends: no
  tags:
    - track_login

- name: Copy track-login
  template:
    src: usr/local/sbin/track-login.j2
    dest: /usr/local/sbin/track-login
    owner: root
    group: root
    mode: 0700
  tags:
    - track_login

- name: Tell PAM to run track-login
  lineinfile:
    path: "{{ item }}"
    regexp: '/usr/local/sbin/track-login'
    line: "session optional        pam_exec.so /usr/local/sbin/track-login"
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/sudo
  tags:
    - track_login
