---
- name: Update aliases
  shell: /usr/bin/newaliases

- name: Restart postfix
  service: name=postfix state=restarted

- name: Restart sshd
  service: name=sshd state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart sshd
  shell: "launchctl stop /System/Library/LaunchDaemons/ssh.plist && launchctl start /System/Library/LaunchDaemons/ssh.plist"
  when: ansible_os_family == 'Darwin'

- name: Restart fail2ban
  service: name=fail2ban state=restarted

- name: Restart prometheus-node-exporter
  service: name=prometheus-node-exporter state=restarted
