- name: Update aliases
  shell: /usr/bin/newaliases

- name: Restart postfix
  service: name=postfix state=restarted

- name: Restart sshd Debian
  service: name=sshd state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart sshd Darwin
  # shell: "launchctl stop /System/Library/LaunchDaemons/ssh.plist; launchctl start /System/Library/LaunchDaemons/ssh.plist"
  shell: "launchctl stop com.openssh.sshd; launchctl start com.openssh.sshd"
  when: ansible_os_family == 'Darwin'

- name: Restart fail2ban
  service: name=fail2ban state=restarted

- name: Restart prometheus-node-exporter Debian
  service: name=prometheus-node-exporter state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart prometheus-node-exporter Darwin
  shell: "launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.node_exporter.plist; launchctl stop homebrew.mxcl.node_exporter; launchctl start homebrew.mxcl.node_exporter"
  when: ansible_os_family == 'Darwin'

# Darwin only
- name: Reload pfconf
  shell: "pfctl -f /etc/pf.conf && pfctl -E"
