---
- name: Update aliases
  shell: /usr/bin/newaliases

- name: Restart postfix
  service: name=postfix state=restarted

- name: Restart sshd
  service: name=sshd state=restarted
  changed_when: False

- name: Restart fail2ban
  service: name=fail2ban state=restarted
