# `passwd -l` disables an account by changing the password to a value which matches no possible encrypted value.
- name: Base - Security - sshd - Lock the password for the root user
  user:
    name: root
    password_lock: yes

- name: Base - Security - sshd - Remove junk from /etc/ssh/
  file:
    path: /etc/ssh/{{ item }}
    state: absent
  with_items:
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
  notify:
    - Restart sshd

- name: Base - Security - sshd - Install libpam-google-authenticator
  package:
    name: libpam-google-authenticator
    state: latest
  notify:
    - Restart sshd

- name: Update /etc/pam.d/sshd to use pam_google_authenticator
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^auth required pam_google_authenticator.so'
    line: 'auth required pam_google_authenticator.so'
  notify:
    - Restart sshd

- name: Update /etc/pam.d/sshd to not ask for passwords
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '@include common-auth'
    line: '#@include common-auth'
  notify:
    - Restart sshd


# This is a cool post on changing the sshd port via ansible: https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/
# I'm not using it because it makes it harder to use firewalls.

# Use a custom, secure sshd config
# NOTE: The fact that we are running this ansible code means that we can ssh as root,
# so we allow that in this config
# Note: We do NOT include this template with this role, so that the role can be public while keeping the
# slightly-confidential sshd settings more private.
- template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart sshd
