- name: Install unattended-upgrades
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Install unattended upgrades config
  template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Install unattended upgrades config
  copy:
    src: etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
