- name: "Security : Upgrade  : Install aptitude before performing any bulk upgrades"
  apt:
    name: aptitude
    state: present
    update_cache: yes
    install_recommends: no

- name: "Security : Upgrade : Upgrade APT to the latest packages"
  apt:
    upgrade: safe
