#!/bin/bash

# Exit immediately if any command fails.
set -e

# Print a message to stderr when attempting to expand a variable that is not set. Also, immediately exit.
set -u

# Cause pipelines to fail on the first command which fails instead of dying later on down the pipeline.
set -o pipefail

grep 'PermitRootLogin' /etc/ssh/sshd_config
sed -i '/^PermitRootLogin*/c\PermitRootLogin yes' /etc/ssh/sshd_config
grep 'PermitRootLogin' /etc/ssh/sshd_config

# grep 'AllowUsers' /etc/ssh/sshd_config
# sed -i '/^AllowUsers*/c\AllowUsers djr root' /etc/ssh/sshd_config
# grep 'AllowUsers' /etc/ssh/sshd_config

grep 'AuthenticationMethods' /etc/ssh/sshd_config
sed -i '/^AuthenticationMethods*/c\AuthenticationMethods publickey' /etc/ssh/sshd_config
grep 'AuthenticationMethods' /etc/ssh/sshd_config

service sshd restart
