# Firewall should be first, as soon as we have the public ip from get_facts
- include: 1-firewall.yml

# upgrade
- include: 2-upgrade.yml

# add custom admin user, and lock down root
- include: 3-admin_users.yml

# sshd updates for security, so do this early
- include: 3-sshd.yml

# unattended-upgrades
- include: 4-unattended-upgrades.yml

# fail2ban is not needed until we open the firewall to services, so this can be near
# the end of the security section.
- include: 5-fail2ban.yml
