# Firewall should be first, as soon as we have the public ip from get_facts
- include: 1-firewall.yml

# upgrade
- include: 2-upgrade.yml

# add custom admin user
- include: 3-create_admin_user.yml

- include: 4-disable_root.yml

# sshd updates for security, so do this early
- include: 5-sshd.yml

# unattended-upgrades
- include: 6-unattended-upgrades.yml

# fail2ban is not needed until we open the firewall to services, so this can be near
# the end of the security section.
- include: 7-fail2ban.yml
