- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add custom admin user
  user:
    name: "{{ admin_username }}"
    shell: /bin/bash
    groups: wheel
    append: yes

- name: Install authorized_keys
  copy:
    src: .ssh/authorized_keys
    dest: /home/{{ admin_username }}/.ssh/authorized_keys
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: 0644  

- name: Get the value for the grace period
  shell: "echo $(($(date +'%s') + 3600))"
  check_mode: no
  register: google_authenticator_grace_period
  changed_when: false

- name: "Set google_authenticator_grace_period"
  set_fact:
    google_authenticator_grace_period: "{{ google_authenticator_grace_period.stdout }}"

- name: Debug google_authenticator_grace_period
  debug:
    var: google_authenticator_grace_period
    verbosity: "1"
  when: not ansible_check_mode

- name: Install .google_authenticator
  template:
    src: secrets/.google_authenticator.j2
    dest: /home/{{ admin_username }}/.google_authenticator
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: 0400
    force: no
  diff: False
  no_log: True
  when: not ansible_check_mode
