- name: Set permissions for .ssh
  file:
    path: /Users/{{ admin_username }}/.ssh
    state: directory
    owner: "{{ admin_username }}"
    group: staff
    mode: 0700

- name: Install authorized_keys
  template:
    src: .ssh/authorized_keys
    dest: /Users/{{ admin_username }}/.ssh/authorized_keys
    owner: "{{ admin_username }}"
    group: staff
    mode: 0600

  # Hides the account (10.10 and above)
- name: Check if user is hidden
  shell: dscl . read /Users/{{ admin_username }} IsHidden | awk '{print $2}'
  register: admin_user_hidden_reg
  check_mode: no
  changed_when: false
  when: not (do_not_hide_admin_user | default(False))

- name: Create user
  command: dscl . create /Users/{{ admin_username }} IsHidden 1
  when: not (do_not_hide_admin_user | default(False)) and (admin_user_hidden_reg.stdout != "1")

# mv /Users/$LOCAL_ADMIN_SHORTNAME /var/$LOCAL_ADMIN_SHORTNAME # Moves the admin home folder to /var
# dscl . -create /Users/$LOCAL_ADMIN_SHORTNAME NFSHomeDirectory /var/$LOCAL_ADMIN_SHORTNAME # Create new home dir attribute
# dscl . -delete "/SharePoints/$LOCAL_ADMIN_FULLNAME's Public Folder" # Removes the public folder sharepoint for the local admin

- name: Allow admin_username user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ admin_username }}'
    line: '{{ admin_username }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  when: not (deny_passwordless_sudo_for_admin | default(False))
