# `passwd -l` disables an account by changing the password to a value which matches no possible encrypted value.
- name: "Security : sshd : Lock the password for the root user"
  user:
    name: root
    password_lock: yes

- name: Install enable_root_ssh
  copy:
    src: enable_root_ssh
    dest: /usr/local/sbin/enable_root_ssh
    owner: root
    group: root
    mode: 0700

# Use a custom, secure sshd config
# Note: We do NOT include this template with this role, so that the role can be public while keeping the
# slightly-confidential sshd settings more private.
- name: Install sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart sshd

- name: Update /etc/pam.d/sshd to use pam_google_authenticator
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^auth required pam_google_authenticator.so'
    line: 'auth required pam_google_authenticator.so grace_period=3600'
  notify:
    - Restart sshd
