# Instead of using libpam-google-authenticator from the apt, I am using a version I compiled myself on Apr 11, 2019.
# This is because it includes the grace_period feature.

# - name: "Security : sshd : Install libpam-google-authenticator"
#   apt:
#     name: libpam-google-authenticator
#     state: latest
#     install_recommends: no
#   notify:
#     - Restart sshd
- name: Install pam_google_authenticator.la
  copy:
    src: lib/x86_64-linux-gnu/security/{{ item }}
    dest: /lib/x86_64-linux-gnu/security/
    owner: root
    group: root
    mode: 0644
  with_items:
    - pam_google_authenticator.la
    - pam_google_authenticator.so
- name: Install pam_google_authenticator.la
  copy:
    src: usr/bin/google-authenticator
    dest: /usr/bin/google-authenticator
    owner: root
    group: root
    mode: 0755

- name: Update /etc/pam.d/sshd to not ask for passwords
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '@include common-auth'
    line: '#@include common-auth'
  notify:
    - Restart sshd

- name: Update /etc/pam.d/sshd to use pam_google_authenticator
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^auth required pam_google_authenticator.so'
    line: 'auth required pam_google_authenticator.so nullok grace_period=172800'
  notify:
    - Restart sshd

# # This doesn't seem to help with anything, so keeping it disabled for now.
# - name: "Update /etc/pam.d/sshd to include pam_permit.so per the README message here: https://github.com/google/google-authenticator-libpam/commit/5e804ec11104a1ab17ce02d0681130ded037f39b"
#   lineinfile:
#     path: /etc/pam.d/sshd
#     regexp: '^auth required pam_permit.so'
#     line: 'auth required pam_permit.so'
#   notify:
#     - Restart sshd
