- name: "Security : sshd : Remove junk from /etc/ssh/"
  file:
    path: /etc/ssh/{{ item }}
    state: absent
  with_items:
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
  notify:
    - Restart sshd



# - name: "Security : sshd : Install libpam-google-authenticator"
#   apt:
#     name: libpam-google-authenticator
#     state: latest
#     install_recommends: no
#   notify:
#     - Restart sshd

# Instead of using libpam-google-authenticator from the apt, I am using a version I compiled myself on Apr 11, 2019.
# This is because it includes the grace_period feature.
- name: Install pam_google_authenticator.la
  copy:
    src: lib/x86_64-linux-gnu/security/{{ item }}
    dest: /lib/x86_64-linux-gnu/security/
    owner: root
    group: root
    mode: 0644
  with_items:
    - pam_google_authenticator.la
    - pam_google_authenticator.so
- name: Install pam_google_authenticator.la
  copy:
    src: usr/bin/google-authenticator
    dest: /usr/bin/google-authenticator
    owner: root
    group: root
    mode: 0755






# - name: Update /etc/pam.d/sshd to use pam_google_authenticator
#   lineinfile:
#     path: /etc/pam.d/sshd
#     regexp: '^auth required pam_google_authenticator.so'
#     line: 'auth required pam_google_authenticator.so grace_period=3600'
#   notify:
#     - Restart sshd

- name: Update /etc/pam.d/sshd to not ask for passwords
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '@include common-auth'
    line: '#@include common-auth'
  notify:
    - Restart sshd


# This is a cool post on changing the sshd port via ansible: https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/
# I'm not using it because it makes it harder to use firewalls.

# - name: Require 2FA
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^AuthenticationMethods'
#     line: 'AuthenticationMethods publickey,keyboard-interactive'
#   notify:
#     - Restart sshd
