- name: "Security : sshd : Remove junk from /etc/ssh/"
  file:
    path: /etc/ssh/{{ item }}
    state: absent
  with_items:
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
  when: ansible_os_family != 'Darwin'
  notify:
    - Restart sshd Debian
    - Restart sshd Darwin

- name: Get wg ip of current inventory host
  local_action: "shell echo '{{ hostvars[inventory_hostname]['do_name'] }}' | ../bin/names_to_wg_ips"
  changed_when: false
  check_mode: no
  register: wireguard_ip_of_current_host_conversion

- set_fact:
    wireguard_ip_of_current_host: "{{ wireguard_ip_of_current_host_conversion.stdout }}"
  check_mode: no

- name: wireguard_ip_of_current_host
  debug:
    msg: "{{ wireguard_ip_of_current_host }}"
    # verbosity: "1"
  check_mode: no


- name: Install jq homebrew package
  homebrew:
    name: jq
    # state: latest
    # update_homebrew: true
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ homebrew_prefix }}/sbin:{{ ansible_env.PATH }}"
  become: true
  become_user: "{{ admin_username }}"
  when: ansible_os_family == 'Darwin'

- name: Install jq homebrew package
  package:
    name: jq
    # state: latest
  when: ansible_os_family != 'Darwin'

- name: Get tailscale IP
  # shell: tailscale status --json | jq -r '.Self.TailAddr'
  shell: tailscale status --json | jq -r '.TailscaleIPs[]' | grep -P '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
  register: tailscale_ip_v4_reg
  changed_when: false
  check_mode: no
  environment:
    PATH: "{{ homebrew_prefix | default('') }}/bin:{{ homebrew_prefix | default('') }}/sbin:/usr/local/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
- name: tailscale_ip_v4_reg
  debug:
    msg: "{{ tailscale_ip_v4_reg }}"
    # verbosity: "1"
  check_mode: no
- set_fact:
    tailscale_ip_v4: "{{ tailscale_ip_v4_reg.stdout }}"
  check_mode: no
- name: tailscale_ip_v4
  debug:
    msg: "{{ tailscale_ip_v4 }}"
    # verbosity: "1"
  check_mode: no

# Use a custom, secure sshd config
# Note: We do NOT include this template with this role, so that the role can be public while keeping the
# slightly-confidential sshd settings more private.
- name: Install sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    # group: root
    mode: 0644
  notify:
    - Restart sshd Debian
    - Restart sshd Darwin
