- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    cache_valid_time: 3600
    install_recommends: no

- name: Install jail.local
  copy:
    src: etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart fail2ban
