- name: Check if hostname is correct
  shell: scutil --get HostName || true
  register: hostname_reg
  check_mode: no
  changed_when: false

- name: Set hostname
  shell: scutil --set ComputerName "{{ custom_hostname }}" && scutil --set LocalHostName "{{ custom_hostname_restricted_chars }}" && scutil --set HostName "{{ custom_hostname_restricted_chars }}"
  when: custom_hostname is defined and hostname_reg.stdout != custom_hostname
