- name: Install inputrc
  copy:
    src: dot.inputrc
    dest: /home/{{ item }}/.inputrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0400
  with_items:
    - "{{ admin_username }}"
    - "{{ custom_username }}"
  tags:
    - inputrc
